
name: 'dbt_training_nov_2025'
version: '1.0.0'


profile: 'dbt_training_nov_2025'


model-paths: ["models"]


models:
  dbt_training_nov_2025:
    silver_airbnb:
      +schema: 'silver_airbnb'
      +materialized: table
