dbt_training_nov_2025:
  outputs:
    DEV:
      account: IBASILQ-ZG60882
      database: DEV
      password: Ankur@12345678
      role: TRANSFORM
      schema: BRONZE_AIRBNB
      threads: 1
      type: snowflake
      user: asahu
      warehouse: COMPUTE_WH
    UAT:
      account: IBASILQ-ZG60882
      database: uat
      password: dbtPassword123
      role: TRANSFORM
      schema: BRONZE_AIRBNB
      threads: 1
      type: snowflake
      user: dbt
      warehouse: COMPUTE_WH
    PROD:
      account: IBASILQ-ZG60882
      database: prod
      password: dbtPassword123
      role: TRANSFORM
      schema: BRONZE_AIRBNB
      threads: 1
      type: snowflake
      user: dbt
      warehouse: COMPUTE_WH
  target: "{{env_var('DBT_TARGET')}}"